<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%directory}}`.
 */
class m210729_055133_create_directory_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%directory}}', [
            'id' => $this->primaryKey(),
            'name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'surname' => $this->smallInteger()->defaultValue(1)->notNull(),
            'patronymic' => $this->smallInteger()->defaultValue(1)->notNull(),
            'gender' => $this->smallInteger()->defaultValue(1)->notNull(),
            'birthday' => $this->smallInteger()->defaultValue(1)->notNull(),
            'birth_place' => $this->smallInteger()->defaultValue(1)->notNull(),
            'inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'snils' => $this->smallInteger()->defaultValue(1)->notNull(),
            'region' => $this->smallInteger()->defaultValue(1)->notNull(),
            'district' => $this->smallInteger()->defaultValue(1)->notNull(),
            'city' => $this->smallInteger()->defaultValue(1)->notNull(),
            'street' => $this->smallInteger()->defaultValue(1)->notNull(),
            'selo' => $this->smallInteger()->defaultValue(1)->notNull(),
            'house' => $this->smallInteger()->defaultValue(1)->notNull(),
            'corpus' => $this->smallInteger()->defaultValue(1)->notNull(),
            'flat' => $this->smallInteger()->defaultValue(1)->notNull(),
            'index' => $this->integer(),
            'fact_address' => $this->smallInteger()->defaultValue(1)->notNull(),
            'passport_id'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'inter_passsport_id'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'mail'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'phone'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'is_ip'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'is_work'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'changed_fio'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'facsimile' => $this->smallInteger()->defaultValue(1)->notNull(),

            'family_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_surname' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_patronymic' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birthday' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_country' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_series' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_number_act' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_birth_number_act_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'family_given' => $this->smallInteger()->defaultValue(1)->notNull(),

            'brak' => $this->smallInteger()->defaultValue(1)->notNull(),
            'razvod' => $this->smallInteger()->defaultValue(1)->notNull(),

            'bank_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_post_address' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_bic' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_currency'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_date_open' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_balance' => $this->smallInteger()->defaultValue(1)->notNull(),
            'bank_other' => $this->smallInteger()->defaultValue(1)->notNull(),

            'creditor_group' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_commitment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_is_predprin'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_statment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_coutry' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_region' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_district' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_city' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_street' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_house' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_corpus' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_flat' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_post_index' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_sum_statment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_sum_dolg' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_forfeit' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_base' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_base_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_base_num' => $this->smallInteger()->defaultValue(1)->notNull(),
            'creditor_other' => $this->smallInteger()->defaultValue(1)->notNull(),

            'debitor_group' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_commitment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_is_predprin'=> $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_statment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_coutry' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_region' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_district' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_city' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_street' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_house' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_corpus' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_flat' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_post_index' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_sum_statment' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_sum_dolg' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_forfeit' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_base' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_base_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_base_num' => $this->smallInteger()->defaultValue(1)->notNull(),
            'debitor_other' => $this->smallInteger()->defaultValue(1)->notNull(),

            'deal_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'deal_description' => $this->smallInteger()->defaultValue(1)->notNull(),
            'deal_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'deal_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'deal_inn' => $this->smallInteger()->defaultValue(1)->notNull(),

            'enforce_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'enforce_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'enforce_sum' => $this->smallInteger()->defaultValue(1)->notNull(),

            'nalog_work' => $this->smallInteger()->defaultValue(1)->notNull(),
            'nalog_year' => $this->smallInteger()->defaultValue(1)->notNull(),
            'nalog_income' => $this->smallInteger()->defaultValue(1)->notNull(),
            'nalog_nalog' => $this->smallInteger()->defaultValue(1)->notNull(),

            'other_text' => $this->smallInteger()->defaultValue(1)->notNull(),

            'other_shares_creater' => $this->smallInteger()->defaultValue(1)->notNull(),
            'other_shares_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'other_shares_total_count' => $this->smallInteger()->defaultValue(1)->notNull(),
            'other_shares_nominal_cost'  => $this->smallInteger()->defaultValue(1)->notNull(),
            'other_shares_other' => $this->smallInteger()->defaultValue(1)->notNull(),

            'property_group' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_property_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_property_view' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_share' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_other_owners' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_active_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_square' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_reg_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_vin_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_date_sved' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_num_sved' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_coutry' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_region' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_district' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_city' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_street' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_house' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_corpus' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_office' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_post_index' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_cost' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_active_status' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_zalog_name' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_zalog_post_index' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_zalog_dogovor' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_other' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_own_dogovor' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'property_zalog_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'property_zalog' => $this->smallInteger()->defaultValue(1)->notNull(),

            'share_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_location' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_company_capital' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_share' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'share_nominal_cost' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_shares_count' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_total_cost' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_dogovor_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'share_other' => $this->smallInteger()->defaultValue(1)->notNull(),

            'valuable_property_property_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_cost' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_location' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_coutry' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_region' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_district' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_city' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_street' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_house' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_corpus' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_office' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_post_index' =>$this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_org_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_dogovor_number' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_dogovor_date' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_active_status' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_zalog_name' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_zalog_type' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_zalog_inn' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_zalog_address' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_zalog_dogovor' => $this->smallInteger()->defaultValue(1)->notNull(),
            'valuable_property_other' => $this->smallInteger()->defaultValue(1)->notNull(),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%directory}}');
    }
}
