<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DirectorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Directories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="directory-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Directory', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'surname',
            'patronymic',
            'gender',
            //'birthday',
            //'birth_place',
            //'inn',
            //'snils',
            //'region',
            //'district',
            //'city',
            //'street',
            //'selo',
            //'house',
            //'corpus',
            //'flat',
            //'index',
            //'fact_address',
            //'passport_id',
            //'inter_passsport_id',
            //'mail',
            //'phone',
            //'is_ip',
            //'is_work',
            //'changed_fio',
            //'facsimile',
            //'family_type',
            //'family_name',
            //'family_surname',
            //'family_patronymic',
            //'family_birthday',
            //'family_inn',
            //'family_birth_country',
            //'family_birth_series',
            //'family_birth_number',
            //'family_birth_date',
            //'family_birth_number_act',
            //'family_birth_number_act_date',
            //'family_given',
            //'brak',
            //'razvod',
            //'bank_name',
            //'bank_post_address',
            //'bank_number',
            //'bank_bic',
            //'bank_type',
            //'bank_currency',
            //'bank_date_open',
            //'bank_balance',
            //'bank_other',
            //'creditor_group',
            //'creditor_commitment',
            //'creditor_is_predprin',
            //'creditor_statment',
            //'creditor_name',
            //'creditor_inn',
            //'creditor_coutry',
            //'creditor_region',
            //'creditor_district',
            //'creditor_city',
            //'creditor_street',
            //'creditor_house',
            //'creditor_corpus',
            //'creditor_flat',
            //'creditor_post_index',
            //'creditor_sum_statment',
            //'creditor_sum_dolg',
            //'creditor_forfeit',
            //'creditor_base',
            //'creditor_base_date',
            //'creditor_base_num',
            //'creditor_other',
            //'debitor_group',
            //'debitor_commitment',
            //'debitor_is_predprin',
            //'debitor_statment',
            //'debitor_name',
            //'debitor_inn',
            //'debitor_coutry',
            //'debitor_region',
            //'debitor_district',
            //'debitor_city',
            //'debitor_street',
            //'debitor_house',
            //'debitor_corpus',
            //'debitor_flat',
            //'debitor_post_index',
            //'debitor_sum_statment',
            //'debitor_sum_dolg',
            //'debitor_forfeit',
            //'debitor_base',
            //'debitor_base_date',
            //'debitor_base_num',
            //'debitor_other',
            //'deal_type',
            //'deal_description',
            //'deal_date',
            //'deal_name',
            //'deal_inn',
            //'enforce_number',
            //'enforce_date',
            //'enforce_sum',
            //'nalog_work',
            //'nalog_year',
            //'nalog_income',
            //'nalog_nalog',
            //'other_text',
            //'other_shares_creater',
            //'other_shares_type',
            //'other_shares_total_count',
            //'other_shares_nominal_cost',
            //'other_shares_other',
            //'property_group',
            //'property_property_type',
            //'property_property_view',
            //'property_share',
            //'property_other_owners',
            //'property_active_name',
            //'property_square',
            //'property_reg_number',
            //'property_vin_number',
            //'property_date_sved',
            //'property_num_sved',
            //'property_coutry',
            //'property_region',
            //'property_district',
            //'property_city',
            //'property_street',
            //'property_house',
            //'property_corpus',
            //'property_office',
            //'property_post_index',
            //'property_cost',
            //'property_active_status',
            //'property_zalog_name',
            //'property_zalog_post_index',
            //'property_zalog_dogovor',
            //'property_other',
            //'property_own_dogovor',
            //'property_zalog_inn',
            //'property_zalog',
            //'share_name',
            //'share_location',
            //'share_inn',
            //'share_company_capital',
            //'share_share',
            //'share_nominal_cost',
            //'share_shares_count',
            //'share_total_cost',
            //'share_dogovor_number',
            //'share_date',
            //'share_other',
            //'valuable_property_property_type',
            //'valuable_property_name',
            //'valuable_property_cost',
            //'valuable_property_location',
            //'valuable_property_coutry',
            //'valuable_property_region',
            //'valuable_property_district',
            //'valuable_property_city',
            //'valuable_property_street',
            //'valuable_property_house',
            //'valuable_property_corpus',
            //'valuable_property_office',
            //'valuable_property_post_index',
            //'valuable_property_org_name',
            //'valuable_property_dogovor_number',
            //'valuable_property_dogovor_date',
            //'valuable_property_active_status',
            //'valuable_property_zalog_name',
            //'valuable_property_zalog_type',
            //'valuable_property_zalog_inn',
            //'valuable_property_zalog_address',
            //'valuable_property_zalog_dogovor',
            //'valuable_property_other',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>
